### ISSUE TITLE
safelyBounce error:session_start()

### ISSUE THREAD

**Issue by nickchomey** [crowdsecurity/cs-wordpress-bouncer#98]
I'm getting this error in the debug.log. Crowdsec doesn't seem to be connecting/working. 

`safelyBounce error:session_start(): open(/var/lib/lsphp/session/lsphp81/sess_e5go527d5uqf4e32bpos3hqfdm, O_RDWR) failed: No such file or directory (2) (Error level: 2) in file:/wp-content/plugins/crowdsec-bk/inc/Bounce.php(line 326)`

It may also be related to the fact that Crowdsec just doesn't seem to be working at all, which I suspect is because I have an OpenLiteSpeed server. 

I'm happy to provide any details you need and help with debugging.

**Comment by julienloizelet** [comment]
Hi,
thanks for reporting this.

For now, the CrowdSec plugin need to start a session (if not already started) in order to save some data for the captcha process.
This `session_start` is done before all other things, and it seems that it can't be done on your system. 

I will release soon (probably this Thursday) a new version of the plugin that will not use session anymore. 

So this kind of error should disappear with the next release. 

I will let you know when the new version is released.

Thanks

**Comment by julienloizelet** [comment]
Hi @nickchomey,
I just released a 1.5.0 version of the plugin that does not use session anymore.
Could you please test it and let me know if it solves your issue ?

Thanks

**Comment by julienloizelet** [comment]
Hi,
I close this one as the error seems to have disappeared with the new release.
Thanks
